site:
  title: "Raghav Kanda - Resume"
  author: "Raghav Kanda"
  email: "raghavkanda9@gmail.com"
  linkedin: "https://www.linkedin.com/in/raghav-kanda-8840b2205/"
  phone: "+1(647)-219-7831"

output_dir: "docs"

